-- MySQL Script generated by MySQL Workbench
-- 04/19/15 12:01:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stangtang
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stangtang` ;

-- -----------------------------------------------------
-- Schema stangtang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stangtang` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `stangtang` ;

-- -----------------------------------------------------
-- Table `BADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BADMIN` (
  `ADM_ID` INT NOT NULL AUTO_INCREMENT,
  `ADM_NAME` VARCHAR(50) NULL,
  `ADM_PASSWORD` VARCHAR(100) NULL,
  `ADM_EMAIL` VARCHAR(20) NULL,
  `ADM_BLOG` VARCHAR(50) NULL,
  `ADM_QQ` VARCHAR(20) NULL,
  `ADM_WEIXIN` VARCHAR(20) NULL,
  `ADM_WEIBO` VARCHAR(50) NULL,
  `ADM_GITHUB` VARCHAR(50) NULL,
  PRIMARY KEY (`ADM_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `BUSER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BUSER` (
  `USR_ID` INT NOT NULL AUTO_INCREMENT,
  `USR_EMAIL` VARCHAR(50) NULL,
  `USR_NAME` VARCHAR(50) NULL,
  `USR_NICKNAME` VARCHAR(50) NULL,
  `USR_PASSWORD` VARCHAR(100) NULL,
  `USR_HEADIMG` VARCHAR(100) NULL,
  `USR_FROM` VARCHAR(10) NULL,
  `USR_PROFILE` VARCHAR(1000) NULL,
  `USR_REGISTER_DT` DATETIME NULL,
  PRIMARY KEY (`USR_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `RTAG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RTAG` (
  `TAG_ID` INT NOT NULL AUTO_INCREMENT,
  `TAG_NAME` VARCHAR(20) NULL,
  `TAG_DESC` VARCHAR(50) NULL,
  `TAG_CREATE_DT` DATETIME NULL,
  PRIMARY KEY (`TAG_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `BARTICLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BARTICLE` (
  `ART_ID` INT NOT NULL AUTO_INCREMENT,
  `ART_ADM_ID` INT NULL,
  `ART_TAG_ID` INT NULL,
  `ART_AUTHOR` VARCHAR(20) NULL,
  `ART_TITLE` VARCHAR(100) NULL,
  `ART_HEADIMG` VARCHAR(100) NULL,
  `ART_CLICK_NUM` INT NULL,
  `ART_LIKE_NUM` INT NULL,
  `ART_COMMENT_NUM` INT NULL,
  `ART_CONTENT_DESC` VARCHAR(1000) NULL,
  `ART_CREATE_DT` DATETIME NULL,
  `ART_UPDATE_DT` DATETIME NULL,
  PRIMARY KEY (`ART_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `XARTICLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `XARTICLE` (
  `ART_ID` INT NOT NULL,
  `ART_CONTENT_TEXT` TEXT NULL,
  `ART_CONTENT_HTML` TEXT NULL,
  PRIMARY KEY (`ART_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `LARTTAG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LARTTAG` (
  `LAT_ART_ID` INT NOT NULL,
  `LAT_TAG_ID` INT NOT NULL,
  PRIMARY KEY (`LAT_ART_ID`,`LAT_TAG_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `BCOMMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BCOMMENT` (
  `CMT_ID` INT NOT NULL AUTO_INCREMENT,
  `CMT_USR_ID` INT NULL,
  `CMT_ART_ID` INT NULL,
  `CMT_CONTENT` VARCHAR(1000) NULL,
  `CMT_CREATE_DT` DATETIME NULL,
  PRIMARY KEY (`CMT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `SPARAMETER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPARAMETER` (
  `PAR_KEY` VARCHAR(20) NOT NULL,
  `PAR_VALUE` VARCHAR(50) NULL,
  PRIMARY KEY (`PAR_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
